services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3333:3000
    environment:
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SECURITY_COOKIE_SAMESITE=disabled
      - GF_SECURITY_ALLOW_EMBEDDING=true
  
  caddy:
    image: caddy:latest
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro